# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20161017_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_ip', models.CharField(max_length=20)),
                ('in_work', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='manager_options',
        ),
        migrations.AddField(
            model_name='task',
            name='defnode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='moretime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='prime',
            field=models.BooleanField(default=False),
        ),
    ]
