# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_auto_20161018_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_cpu',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='node',
            name='node_ram',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='task_cpu',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='task_ram',
            field=models.IntegerField(default=0),
        ),
    ]
