# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_auto_20161018_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobalLimits',
            new_name='GlobalLimit',
        ),
    ]
