# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_auto_20161018_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned_from', models.DateTimeField(verbose_name='date banned')),
                ('banned_to', models.DateTimeField(verbose_name='date unbanned')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='banned',
        ),
        migrations.AddField(
            model_name='bannedusers',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.User', unique=True),
        ),
    ]
