# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_auto_20161018_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannedusers',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interface.User'),
        ),
    ]
