# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_auto_20161018_1639'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BannedUsers',
            new_name='BannedUser',
        ),
    ]
