# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 14:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0009_auto_20161018_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_cpu',
            new_name='cpu',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_options',
            new_name='options',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_path',
            new_name='path',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_ram',
            new_name='ram',
        ),
        migrations.AddField(
            model_name='task',
            name='date_publish',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 18, 14, 2, 29, 976000, tzinfo=utc), verbose_name='published date'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='in queue', max_length=30),
        ),
    ]
