# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 14:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_auto_20161018_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_publish',
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 18, 14, 6, 53, 964000, tzinfo=utc), verbose_name='published date'),
        ),
    ]
