# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0012_auto_20161019_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='published date'),
        ),
    ]
