# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 06:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0014_auto_20161019_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 19, 6, 48, 4, 5000, tzinfo=utc), verbose_name='published date'),
        ),
    ]
