# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 07:16
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('interface', '0016_auto_20161019_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banned',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('banned_to', models.DateTimeField(default=datetime.datetime(2016, 10, 21, 7, 16, 24, 114000, tzinfo=utc), verbose_name='date unbanned')),
                ('banned_from', models.DateTimeField(default=datetime.datetime(2016, 10, 19, 7, 16, 24, 114000, tzinfo=utc), verbose_name='date unbanned')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='banned_from',
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 19, 7, 16, 24, 115000, tzinfo=utc), verbose_name='published date'),
        ),
    ]
