# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 07:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0018_auto_20161019_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banned',
            name='banned_from',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 20, 7, 17, 31, 130000, tzinfo=utc), verbose_name='date banned'),
        ),
        migrations.AlterField(
            model_name='banned',
            name='banned_to',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 22, 7, 17, 31, 131000, tzinfo=utc), verbose_name='date unbanned'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 20, 7, 17, 31, 132000, tzinfo=utc), verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='options',
            field=models.TextField(max_length=255),
        ),
    ]
