# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 08:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0019_auto_20161020_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banned',
            name='banned_from',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 20, 8, 7, 0, 770000, tzinfo=utc), verbose_name='date banned'),
        ),
        migrations.AlterField(
            model_name='banned',
            name='banned_to',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 22, 8, 7, 0, 770000, tzinfo=utc), verbose_name='date unbanned'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 20, 8, 7, 0, 771000, tzinfo=utc), verbose_name='published date'),
        ),
    ]
