# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 09:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0022_auto_20161020_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banned',
            name='banned_from',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 20, 9, 31, 4, 43000, tzinfo=utc), verbose_name='date banned'),
        ),
        migrations.AlterField(
            model_name='banned',
            name='banned_to',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 22, 9, 31, 4, 43000, tzinfo=utc), verbose_name='date unbanned'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 20, 9, 31, 4, 44000, tzinfo=utc), verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='options',
            field=models.TextField(default='none', max_length=255),
        ),
    ]
