# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 13:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0024_auto_20161020_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banned',
            name='banned_from',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 20, 13, 33, 40, 409000, tzinfo=utc), verbose_name='date banned'),
        ),
        migrations.AlterField(
            model_name='banned',
            name='banned_to',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 22, 13, 33, 40, 409000, tzinfo=utc), verbose_name='date unbanned'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 20, 13, 33, 40, 410000, tzinfo=utc), verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='node_id',
            field=models.IntegerField(default=-1),
        ),
    ]
