# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 08:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0026_auto_20161026_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banned',
            name='banned_from',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 26, 8, 13, 35, 210000, tzinfo=utc), verbose_name='date banned'),
        ),
        migrations.AlterField(
            model_name='banned',
            name='banned_to',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 28, 8, 13, 35, 210000, tzinfo=utc), verbose_name='date unbanned'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 26, 8, 13, 35, 212000, tzinfo=utc), verbose_name='published date'),
        ),
    ]
