# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 08:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0027_auto_20161026_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='banned',
            name='banned_from',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 26, 8, 14, 12, 836000, tzinfo=utc), verbose_name='date banned'),
        ),
        migrations.AlterField(
            model_name='banned',
            name='banned_to',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 28, 8, 14, 12, 836000, tzinfo=utc), verbose_name='date unbanned'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 26, 8, 14, 12, 838000, tzinfo=utc), verbose_name='published date'),
        ),
    ]
